### ISSUE TITLE
Modal's "transform: translate" to center it makes text blurry

### ISSUE THREAD

**Issue by AAugustBentley** [iTwin/iTwinUI#1551]
We have a modal that has a few tabs with different data shown in a table.
However, text in a table becomes very blurry when adding a table height (so that it would not overflow and we would have a scrollbar to look through all entries in the table).
![image](https://github.com/iTwin/iTwinUI/assets/129863171/31544f3f-fa8d-4dbd-961e-14164cae5c85)

Even without height, it does not look clear enough.
![image](https://github.com/iTwin/iTwinUI/assets/129863171/2790db76-7918-4e87-9886-74a249775185)

I tried adding `backface-visibility: hidden;`, `-webkit-font-smoothing: subpixel-antialiased;`, overwritting transform with `transform: translate(calc(-50% + 0.5px), calc(-50% + 0.5px))` and other things but nothing worked. I think this happens because with a lot of elements put in each other, those "transform translate" decimal sizes become worse than if they were on top level (for example, tabs' text looks fine).

The solution for now I came up with for now is removing transform and changing it to `display: flex` and then centering with `justify-content` and `align-items` in the modal's wrapper. The only problem I noticed with that is that if a modal has buttons with navigation when closing the current and loading another modal, there is a noticeable blinking.

Could anyone check this?

**Comment by mayank99** [comment]
hey @AAugustBentley, thanks for the issue. It is very hard to tell what part is blurred just from the screenshots and we don't have the ability to debug either. Could you try to recreate this scenario in a sandbox or at least share a deployed url? And could you also share information about your environment (OS, browser, screen resolution, zoom level)?

**Comment by mayank99** [comment]
Should be fixed in 3.0.6

**Comment by mattl-bentley** [comment]
@mayank99 I'm in the process of updating to 2.12.17 and noticed this issue. Can this fix be backported to 2x?

**Comment by mattl-bentley** [comment]
thanks @mayank99

**Comment by HaveSpacesuit** [comment]
@mayank99 It looks like this is still an issue when there is a table inside an expandable block. Not sure how common the use case is, but maybe it means there are other situations when it is a problem?

![image](https://github.com/iTwin/iTwinUI/assets/15036346/5311a6bc-d63f-45e9-9277-d966c46e7de1)

**Comment by mayank99** [comment]
> It looks like this is still an issue when there is a table inside an expandable block. Not sure how common the use case is, but maybe it means there are other situations when it is a problem?

Are you able to create a repro?

**Comment by HaveSpacesuit** [comment]
It took a while, but I found that if you change `height: 100dvh` to `height: 100%` in the demo app, it causes blurriness. Unfortunately, trying to use `height: 100dvh` in my app doesn't seem to make any difference, so there are probably other things going on. (But this component is only used for QA anyway, so not an immediate issue for customers.)

https://stackblitz.com/edit/github-fsmjja

![Blurry table in expander](https://github.com/iTwin/iTwinUI/assets/15036346/cf636fde-9e86-47f4-b6ea-80acd4841609)

**Comment by mayank99** [comment]
> I found that if you change `height: 100dvh` to `height: 100%` in the demo app, it causes blurriness
> 
> [stackblitz.com/edit/github-fsmjja](https://stackblitz.com/edit/github-fsmjja)

Thanks for the repro. I'll reopen this issue as it was confirmed on Windows.

Some other interesting observations:

- I found that using dvh actually can sometimes make it *less* blurry?
  <details><summary>Recording</summary>
  
  https://github.com/iTwin/iTwinUI/assets/9084735/c9068752-f118-403c-978d-daab70055120
  
  </details>

- @Ben-Pusey-Bentley found that removing the `ExpandableBlock` can sometimes fix the blurring.
  <details><summary>Recording</summary>
  
  https://github.com/iTwin/iTwinUI/assets/9084735/b0a8e565-30c7-430b-a982-61122c103c02
  
  </details>

---

> But this component is only used for QA anyway, so not an immediate issue for customers.

This is good to know. I guess we'll keep an eye out for any similar future reports, and prioritize based on that. For now we can leave it be.

**Comment by AAugustBentley** [comment]
Started working on another modal and I still see problems with blurriness in tables, this time it's the icon button (in a sticky column) and information panel
![image](https://github.com/iTwin/iTwinUI/assets/129863171/083ae9f5-d7b5-49c9-99b3-54566412bb84)

Pulled the newest itwinui-react version (v3.6.0) just to check if it changes anything. This is going to be released for users, so maybe this item could be prioritized?

**Comment by HaveSpacesuit** [comment]
I also noticed a table in an info panel was blurry.

**Comment by AAugustBentley** [comment]
> Started working on another modal and I still see problems with blurriness in tables, this time it's the icon button (in a sticky column) and information panel ![image](https://private-user-images.githubusercontent.com/129863171/314083175-083ae9f5-d7b5-49c9-99b3-54566412bb84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTI5OTIsIm5iZiI6MTcxMDk1MjY5MiwicGF0aCI6Ii8xMjk4NjMxNzEvMzE0MDgzMTc1LTA4M2FlOWY1LWQ3YjUtNDljOS05OWIzLTU0NTY2NDEyYmI4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxNjM4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjE3NzIzNjNmMDJjZWI5ZWU1YTI1NjM4YzU0ZjI4ZDc3N2QwYjcxZDY2MzY0NzE5MmFmNjNmYzM2YTBhM2UyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kETvBTE86_qUz_c4h8-jGU5jfE8vNNFCCqY8OJ72698)
> 
> Pulled the newest itwinui-react version (v3.6.0) just to check if it changes anything. This is going to be released for users, so maybe this item could be prioritized, please?


Reproduced code: https://stackblitz.com/edit/github-acfvki?file=src%2FApp.tsx

**Comment by mayank99** [comment]
@AAugustBentley Could you clarify what part is blurry? Multiple members of our team checked and couldn't find the issue

**Comment by mayank99** [comment]
Something common to Dialog/InformationPanel/ExpandableBlock is that they all use `transform: translate`. My guess is that when two or more such instances are combined, it can cause blurring.

Our team was able to confirm it in some situations (the repro links definitely help). But ultimately this is just a (minor) bug in Chrome on Windows. We can't address the root cause, only work around it.

So there isn't much we can do right now, but in the future we'll keep this in mind when we refactor our Dialog (and maybe other components) to use flex layout. This issue can remain open for now.

**Comment by AAugustBentley** [comment]
We made a workaround to not use transform from our side to fix blurriness issue, if anyone is interested. The only issue will probably would be that the modal is going to be in the middle.

add css on modal wrapper `_iui3-dialog-wrapper`
![image](https://github.com/iTwin/iTwinUI/assets/129863171/8b29107b-93b2-4e37-9901-ee768806a22d)

then on the modal itself (`iui-dialog`)
![image](https://github.com/iTwin/iTwinUI/assets/129863171/692c9006-be5a-4edb-897b-7a71ebb4bcf4)

**Comment by HaveSpacesuit** [comment]
Here is another example of blurry text on a tile inside a draggable dialog.
https://stackblitz.com/edit/github-rfuo7n?file=src%2FApp.tsx

![image](https://github.com/iTwin/iTwinUI/assets/15036346/1eabc849-f160-4c9b-944b-b1f3c0435452)

**Comment by FlyersPh9** [comment]
iTwinUI is now in maintenance mode per [the support policy](https://github.com/iTwin/iTwinUI/wiki/Support-policy), with [StrataKit](https://github.com/iTwin/stratakit) replacing it as the primary design system.
